# -*- coding: utf-8 -*-
"""Tarea13 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZX6ha9ilYCpx8TrA6lnIylRsdwNWbc9

# **Ejercicio 13**

Escribe un programa en Python que muestra al usario el menu siguiente:


1.   Saludar.
2.   Mostrar un mensaje.
3.   Salir

Mientras el usario no presione la opción **3**, el programa debe seguir mandando el menu. Si el usario presiona **1**, el programa pide el nombre al usario y muetra a pantalla un saludo con su nombre. Si el usario presiona **2**, el programa debe mandar a panta lla un mensaje personalizado por ustedes.

Cada una de las lienas de código escritas deben estar acompañadas de un comentario que explique su uso.
"""

#Escriebe tu código.
# Importamos la función input para recibir datos del usuario
# Inicializamos una variable para controlar la opción del usuario
opcion = 0  # Al comenzar, la opción es 0 para entrar al ciclo

# Usamos un ciclo while para mostrar el menú mientras el usuario no elija salir
while opcion != 3:
    # Mostramos el menú de opciones

    print("1. Saludar")
    print("2. Mostrar un mensaje")
    print("3. Salir")

    # Pedimos al usuario que elija una opción
    opcion = int(input("Elige una opción (1-3): "))  # Convertimos la entrada a entero

    # Verificamos si la opción es 1
    if opcion == 1:
        # Pedimos el nombre del usuario
        nombre = input("¿Cuál es tu nombre? ")
        # Mostramos un saludo personalizado
        print("¡Hola, " + nombre + "! Encantado de saludarte.")

    # Verificamos si la opción es 2
    elif opcion == 2:
        # Mostramos un mensaje personalizado
        print("Este es un mensaje especial: ¡Sigue aprendiendo y nunca te rindas!")

    # Verificamos si la opción es 3
    elif opcion == 3:
        # Mostramos un mensaje de despedida
        print("¡Hasta luego! Gracias por usar el programa.")

    # Si la opción no es válida
    else:
        # Informamos al usuario que la opción no es válida
        print("Opción no válida. Por favor elige entre 1 y 3.")